In [167]:
import pandas as pd

daily_return_df = pd.read_csv('sp500_joined_daily_returns_yahoo.csv')
daily_return_df.set_index('Date', inplace=True)
daily_return_df

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,XEL,XRX,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS,SPY
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,-0.420879,-0.395606,NaN,-0.014346,NaN,-0.064721,-0.031990,0.035491,NaN,-0.255485,...,-0.608536,-0.304356,-0.310023,NaN,-0.283451,-0.034815,NaN,-0.322457,NaN,-0.335147
2000-01-04,-0.424806,-0.399022,NaN,-0.037162,NaN,-0.114259,-0.053371,-0.033058,NaN,-0.256409,...,-0.587705,-0.358993,-0.290556,NaN,-0.268203,-0.014428,NaN,-0.303260,NaN,-0.340144
2000-01-05,-0.396778,-0.384488,NaN,0.054945,NaN,-0.093212,0.044063,0.032258,NaN,-0.224806,...,-0.580057,-0.291187,-0.297410,NaN,-0.259446,0.066588,NaN,-0.279348,NaN,-0.321987
2000-01-06,-0.370289,-0.371148,NaN,0.023050,NaN,-0.114423,-0.002024,0.032258,NaN,-0.228983,...,-0.598170,-0.322374,-0.341881,NaN,-0.260714,-0.041970,NaN,-0.269102,NaN,-0.331391
2000-01-07,-0.401052,-0.373645,NaN,-0.003472,NaN,-0.089726,0.044336,0.054767,NaN,-0.214733,...,-0.595659,-0.311802,-0.214726,NaN,-0.275959,-0.006455,NaN,-0.281024,NaN,-0.296027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-11-30,-0.017295,0.004176,-0.005137,0.001388,0.000120,0.014811,-0.003187,0.061033,-0.010915,-0.025274,...,-0.003698,-0.047018,0.058622,-0.008779,-0.003766,-0.000159,-0.007455,-0.019563,-0.012925,-0.002122
2020-12-01,-0.021237,-0.006866,-0.009614,-0.014332,0.003022,-0.000125,-0.005934,0.004119,0.023747,-0.002904,...,0.011683,-0.006278,0.005517,-0.004614,-0.004680,-0.024788,-0.029171,0.013661,-0.001732,0.001231
2020-12-02,0.009339,-0.001477,0.009519,-0.011073,-0.004188,-0.007150,0.011752,0.009151,-0.018058,0.033203,...,0.007334,0.014324,0.008985,-0.000935,-0.008407,-0.009441,0.017130,0.040000,-0.012733,0.005400
2020-12-03,0.004619,-0.005733,-0.002476,0.011562,-0.000280,-0.006557,0.004293,-0.018605,0.010091,0.002369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000027
2020-12-04,0.001917,0.007658,0.021520,0.025737,0.012869,0.027439,0.000679,0.015770,0.016738,-0.008004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.004438

### Follow The Leader ###

In [ ]:
import numpy as np

windows = [5,10,20,40,60]
W = pd.DataFrame().reindex(columns = daily_return_df.columns, index = windows)
for col in W.columns:
    W[col].values[:] = 0
FTL_betas = pd.DataFrame().reindex(columns = daily_return_df.columns, index = daily_return_df.index)
for date in daily_return_df.index:
    print("W on {1}: {0}".format(W, date))
    print("W.idxmin(): {0}".format(W.idxmin()))
    min_window_df = W.idxmin()
    print("min window: {0}".format(min_window_df))
    for ticker in daily_return_df.columns:
        window_for_ticker = min_window_df[ticker]
        act_beta = daily_return_df[ticker].rolling(window=window_for_ticker).cov(daily_return_df['SPY']).div(daily_return_df['SPY'].rolling(window=window_for_ticker).var(), axis=0)
        FTL_betas[ticker][date] = act_beta[date]
        
        # refresh weights
        act_beta_error = (daily_return_df[ticker] - act_beta.mul(daily_return_df['SPY'].mean(), axis=0)) ** 2
        
        if not np.isnan(act_beta_error[date]):
#             print("act beta: {0}".format(act_beta_error[date]))
#             print(":::::::::::::W[ticker][window_for_ticker]: {}".format(W[ticker][window_for_ticker]))
            W[ticker][window_for_ticker] += act_beta_error[date]
#             print(":::::::::::::W[ticker][window_for_ticker]: {}".format(W[ticker][window_for_ticker]))
#         if ticker == "ABBV":
#             print("ABBV ==================")
#             print(date)
#             print(act_beta_error)
#             print(W[ticker])
#             print("ABBV ==================")
            
#         else:
#             print(ticker)
        
        for window in windows:
            if window == window_for_ticker:
                continue
            beta = daily_return_df[ticker].rolling(window=window).cov(daily_return_df['SPY']).div(daily_return_df['SPY'].rolling(window=window).var(), axis=0)
            beta_error = (daily_return_df[ticker] - beta.mul(daily_return_df['SPY'].mean(), axis=0)) ** 2
#             if not np.isnan(beta_error[date]):
#                 W[ticker] += beta_error[date]
    print("//////////////////////////////////")

W on 2000-01-03:     MMM  ABT  ABBV  ABMD  ACN  ATVI  ADBE  AMD  AAP  AES  ...  XEL  XRX  XLNX  \
5   0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
10  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
20  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
40  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
60  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0

    XYL  YUM  ZBRA  ZBH  ZION  ZTS  SPY
5   0.0  0.0   0.0  0.0   0.0  0.0  0.0
10  0.0  0.0   0.0  0.0   0.0  0.0  0.0
20  0.0  0.0   0.0  0.0   0.0  0.0  0.0
40  0.0  0.0   0.0  0.0   0.0  0.0  0.0
60  0.0  0.0   0.0  0.0   0.0  0.0  0.0

[5 rows x 506 columns]
W.idxmin(): MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
min window: MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
ABBV ==================
2000-01-03
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-04:     MMM  ABT  ABBV  ABMD  ACN  ATVI  ADBE  AMD  AAP  AES  ...  XEL  XRX  XLNX  \
5   0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
10  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
20  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
40  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
60  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0

    XYL  YUM  ZBRA  ZBH  ZION  ZTS  SPY
5   0.0  0.0   0.0  0.0   0.0  0.0  0.0
10  0.0  0.0   0.0  0.0   0.0  0.0  0.0
20  0.0  0.0   0.0  0.0   0.0  0.0  0.0
40  0.0  0.0   0.0  0.0   0.0  0.0  0.0
60  0.0  0.0   0.0  0.0   0.0  0.0  0.0

[5 rows x 506 columns]
W.idxmin(): MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
min window: MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
ABBV ==================
2000-01-04
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-05:     MMM  ABT  ABBV  ABMD  ACN  ATVI  ADBE  AMD  AAP  AES  ...  XEL  XRX  XLNX  \
5   0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
10  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
20  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
40  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
60  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0

    XYL  YUM  ZBRA  ZBH  ZION  ZTS  SPY
5   0.0  0.0   0.0  0.0   0.0  0.0  0.0
10  0.0  0.0   0.0  0.0   0.0  0.0  0.0
20  0.0  0.0   0.0  0.0   0.0  0.0  0.0
40  0.0  0.0   0.0  0.0   0.0  0.0  0.0
60  0.0  0.0   0.0  0.0   0.0  0.0  0.0

[5 rows x 506 columns]
W.idxmin(): MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
min window: MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
ABBV ==================
2000-01-05
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-06:     MMM  ABT  ABBV  ABMD  ACN  ATVI  ADBE  AMD  AAP  AES  ...  XEL  XRX  XLNX  \
5   0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
10  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
20  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
40  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
60  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0

    XYL  YUM  ZBRA  ZBH  ZION  ZTS  SPY
5   0.0  0.0   0.0  0.0   0.0  0.0  0.0
10  0.0  0.0   0.0  0.0   0.0  0.0  0.0
20  0.0  0.0   0.0  0.0   0.0  0.0  0.0
40  0.0  0.0   0.0  0.0   0.0  0.0  0.0
60  0.0  0.0   0.0  0.0   0.0  0.0  0.0

[5 rows x 506 columns]
W.idxmin(): MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
min window: MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
ABBV ==================
2000-01-06
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-07:     MMM  ABT  ABBV  ABMD  ACN  ATVI  ADBE  AMD  AAP  AES  ...  XEL  XRX  XLNX  \
5   0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
10  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
20  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
40  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0
60  0.0  0.0   0.0   0.0  0.0   0.0   0.0  0.0  0.0  0.0  ...  0.0  0.0   0.0

    XYL  YUM  ZBRA  ZBH  ZION  ZTS  SPY
5   0.0  0.0   0.0  0.0   0.0  0.0  0.0
10  0.0  0.0   0.0  0.0   0.0  0.0  0.0
20  0.0  0.0   0.0  0.0   0.0  0.0  0.0
40  0.0  0.0   0.0  0.0   0.0  0.0  0.0
60  0.0  0.0   0.0  0.0   0.0  0.0  0.0

[5 rows x 506 columns]
W.idxmin(): MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
min window: MMM     5
ABT     5
ABBV    5
ABMD    5
ACN     5
       ..
ZBRA    5
ZBH     5
ZION    5
ZTS     5
SPY     5
Length: 506, dtype: int64
ABBV ==================
2000-01-07
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-10:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE      AMD  AAP  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.08509  0.0
10  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0

         AES  ...       XEL       XRX     XLNX  XYL       YUM      ZBRA  ZBH  \
5   0.002621  ...  0.342175  0.039387  0.03338  0.0  0.083726  0.014248  0.0
10  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
20  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
40  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
60  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0

        ZION  ZTS       SPY
5   0.032282  0.0  0.013536
10  0.000000  0.0  0.000000
20  0.000000  0.0  0.000000
40  0.000000  0.0  0.000000
60  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-01-10
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-01-11:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE      AMD  AAP  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.08509  0.0
10  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0

         AES  ...       XEL       XRX     XLNX  XYL       YUM      ZBRA  ZBH  \
5   0.002621  ...  0.342175  0.039387  0.03338  0.0  0.083726  0.014248  0.0
10  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
20  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
40  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
60  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0

        ZION  ZTS       SPY
5   0.032282  0.0  0.013536
10  0.000000  0.0  0.000000
20  0.000000  0.0  0.000000
40  0.000000  0.0  0.000000
60  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-01-11
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-12:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE      AMD  AAP  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.08509  0.0
10  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0

         AES  ...       XEL       XRX     XLNX  XYL       YUM      ZBRA  ZBH  \
5   0.002621  ...  0.342175  0.039387  0.03338  0.0  0.083726  0.014248  0.0
10  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
20  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
40  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
60  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0

        ZION  ZTS       SPY
5   0.032282  0.0  0.013536
10  0.000000  0.0  0.000000
20  0.000000  0.0  0.000000
40  0.000000  0.0  0.000000
60  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-01-12
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-13:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE      AMD  AAP  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.08509  0.0
10  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0

         AES  ...       XEL       XRX     XLNX  XYL       YUM      ZBRA  ZBH  \
5   0.002621  ...  0.342175  0.039387  0.03338  0.0  0.083726  0.014248  0.0
10  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
20  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
40  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
60  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0

        ZION  ZTS       SPY
5   0.032282  0.0  0.013536
10  0.000000  0.0  0.000000
20  0.000000  0.0  0.000000
40  0.000000  0.0  0.000000
60  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-01-13
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-14:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE      AMD  AAP  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.08509  0.0
10  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.00000  0.0

         AES  ...       XEL       XRX     XLNX  XYL       YUM      ZBRA  ZBH  \
5   0.002621  ...  0.342175  0.039387  0.03338  0.0  0.083726  0.014248  0.0
10  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
20  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
40  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0
60  0.000000  ...  0.000000  0.000000  0.00000  0.0  0.000000  0.000000  0.0

        ZION  ZTS       SPY
5   0.032282  0.0  0.013536
10  0.000000  0.0  0.000000
20  0.000000  0.0  0.000000
40  0.000000  0.0  0.000000
60  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     10
ABT     10
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-01-14
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-18:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-18
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-01-19:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-19
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-20:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-20
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-21:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-21
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-24:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-24
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-25:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-25
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-01-26:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-26
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-27:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-27
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-28:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-28
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-01-31:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.000000  0.0  0.000000
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-01-31
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-01:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-01
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-02-02:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-02
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-03:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-03
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-04:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-04
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-07:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-07
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-08:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-08
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-02-09:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-09
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-10:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-10
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-11:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-11
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-14:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-14
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-15:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-15
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-02-16:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-16
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-17:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-17
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-18:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-18
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-22:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-22
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-23:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-23
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-02-24:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-24
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-25:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-25
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-28:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-28
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-02-29:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.000000  0.0  0.000000
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-02-29
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-01:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-01
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-03-02:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-02
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-03:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-03
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-06:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-06
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-07:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-07
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-08:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-08
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-03-09:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-09
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-10:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-10
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-13:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-13
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-14:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-14
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-15:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-15
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-03-16:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-16
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-17:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-17
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-20:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-20
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-21:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-21
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-22:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-22
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-03-23:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-23
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-24:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-24
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-27:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-27
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-28:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.000000  0.000000   0.0  0.000000  0.0  0.000000  0.000000  0.000000

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.000000  ...  0.000000  0.000000  0.000000  0.0  0.000000  0.000000

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.000000  0.0  0.000000

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-03-28
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-29:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.084679   0.0  0.007813  0.0  0.002548  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.002758  0.0  0.031448  0.051833  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.067527  0.089706   0.0  0.021222  0.0  0.008098  0.071257  0.038752

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.001301  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.002987  0.0  0.044315  0.045574
60  0.0  0.030225  ...  0.315963  0.018843  0.006063  0.0  0.009431  0.000704

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.013536
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.002276  0.0  0.020086

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT      5
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     60
ABT      5
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-03-29
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-03-30:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.314455   0.0  0.007813  0.0  0.053964  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.002793  0.171194  0.119554
20  0.097757  0.102681   0.0  0.016864  0.0  0.031448  0.419110  0.227827
40  0.077245  0.114534   0.0  0.011315  0.0  0.002953  0.054611  0.056742
60  0.143352  0.089706   0.0  0.021222  0.0  0.008098  0.071257  0.068059

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.002621  ...  0.342175  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.013402  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.019457  0.030664  0.0  0.044315  0.045574
60  0.0  0.030225  ...  0.631214  0.033393  0.006063  0.0  0.020200  0.001506

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.033820
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.015350
40  0.0  0.002762  0.0  0.018430
60  0.0  0.006657  0.0  0.020086

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     60
ABBV     5
ABMD     5
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     40
ABT     60
ABBV     5
ABMD     5
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-03-30
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-03-31:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.314455   0.0  0.763110  0.0  0.053964  0.177506  0.085090
10  0.135212  0.098252   0.0  0.044857  0.0  0.069162  0.171194  0.119554
20  0.097757  0.102681   0.0  0.016864  0.0  0.031448  0.419110  0.227827
40  0.129875  0.114534   0.0  0.011315  0.0  0.002953  0.119447  0.065588
60  0.143352  0.189048   0.0  0.021222  0.0  0.008098  0.071257  0.068059

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.004186  ...  0.765543  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.013402  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007615  0.0  0.061583  0.002325
40  0.0  0.042058  ...  0.348097  0.027422  0.030664  0.0  0.044315  0.045574
60  0.0  0.030225  ...  0.631214  0.033393  0.008007  0.0  0.021074  0.002982

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.033820
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.037115
40  0.0  0.003443  0.0  0.018430
60  0.0  0.006657  0.0  0.020086

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     10
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     20
ABT     10
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-03-31
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-03:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.119369  0.314455   0.0  0.763110  0.0  0.053964  0.177506  0.085090
10  0.135212  0.340327   0.0  0.044857  0.0  0.069162  0.171194  0.119554
20  0.148976  0.102681   0.0  0.016864  0.0  0.031448  0.419110  0.227827
40  0.129875  0.114534   0.0  0.018240  0.0  0.020600  0.119447  0.072272
60  0.143352  0.189048   0.0  0.021222  0.0  0.008098  0.158098  0.068059

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  0.765543  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.013402  ...  0.349649  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.007698  0.0  0.061583  0.031034
40  0.0  0.042058  ...  0.644582  0.039790  0.030664  0.0  0.044315  0.045574
60  0.0  0.030225  ...  0.631214  0.033393  0.008007  0.0  0.031706  0.002982

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.033820
10  0.0  0.018880  0.0  0.019763
20  0.0  0.005110  0.0  0.037115
40  0.0  0.007793  0.0  0.037330
60  0.0  0.006657  0.0  0.020086

[5 rows x 506 columns]
W.idxmin(): MMM      5
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    20
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM      5
ABT     20
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    20
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-04-03
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-04:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.314455   0.0  0.763110  0.0  0.053964  0.177506  0.085090
10  0.135212  0.340327   0.0  0.044857  0.0  0.069162  0.171194  0.119554
20  0.148976  0.170244   0.0  0.077315  0.0  0.031448  0.419110  0.227827
40  0.129875  0.114534   0.0  0.018240  0.0  0.020600  0.150035  0.072272
60  0.143352  0.189048   0.0  0.021222  0.0  0.034846  0.158098  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  0.765543  0.039387  0.033380  0.0  0.083726  0.014248
10  0.0  0.206570  ...  0.791185  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.019843  ...  0.354362  0.050034  0.018495  0.0  0.061583  0.031034
40  0.0  0.042058  ...  0.644582  0.039790  0.030664  0.0  0.044315  0.045574
60  0.0  0.030225  ...  0.631214  0.055703  0.008007  0.0  0.047652  0.006501

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.033820
10  0.0  0.018880  0.0  0.038203
20  0.0  0.009014  0.0  0.037115
40  0.0  0.007793  0.0  0.037330
60  0.0  0.006657  0.0  0.020086

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-04-04
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-05:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.314455   0.0  0.763110  0.0  0.053964  0.177506  0.085090
10  0.135212  0.340327   0.0  0.044857  0.0  0.069162  0.171194  0.119554
20  0.148976  0.170244   0.0  0.077315  0.0  0.031448  0.419110  0.227827
40  0.182994  0.186650   0.0  0.029837  0.0  0.037531  0.190320  0.076038
60  0.143352  0.189048   0.0  0.021222  0.0  0.034846  0.158098  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  0.765543  0.425937  0.033380  0.0  0.083726  0.014248
10  0.0  0.206570  ...  0.791185  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.066103  ...  0.678759  0.050034  0.018495  0.0  0.061583  0.031034
40  0.0  0.042058  ...  0.644582  0.039790  0.030664  0.0  0.046515  0.045574
60  0.0  0.030225  ...  0.631214  0.055703  0.018276  0.0  0.047652  0.007563

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.033820
10  0.0  0.018880  0.0  0.038203
20  0.0  0.009014  0.0  0.037115
40  0.0  0.007793  0.0  0.037330
60  0.0  0.008053  0.0  0.042037

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     10
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-04-05
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-04-06:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.314455   0.0  0.763110  0.0  0.053964  0.177506  0.085090
10  0.237439  0.340327   0.0  0.044857  0.0  0.069162  0.171194  0.119554
20  0.148976  0.334404   0.0  0.077315  0.0  0.063811  0.419110  0.227827
40  0.182994  0.186650   0.0  0.029837  0.0  0.037531  0.190320  0.076751
60  0.143352  0.189048   0.0  0.058284  0.0  0.034846  0.268203  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  0.765543  0.425937  0.033380  0.0  0.083726  0.014248
10  0.0  0.206570  ...  0.791185  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.066103  ...  0.678759  0.050034  0.018495  0.0  0.061583  0.031034
40  0.0  0.042058  ...  0.644582  0.051065  0.030664  0.0  0.046858  0.045574
60  0.0  0.074836  ...  0.943136  0.055703  0.018489  0.0  0.047652  0.010029

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.052006
10  0.0  0.018880  0.0  0.038203
20  0.0  0.009014  0.0  0.037115
40  0.0  0.007966  0.0  0.037330
60  0.0  0.008053  0.0  0.042037

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     60
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-04-06
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-07:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.314455   0.0  0.763110  0.0  0.053964  0.177506  0.085090
10  0.237439  0.340327   0.0  0.044857  0.0  0.069162  0.431763  0.119554
20  0.148976  0.334404   0.0  0.077315  0.0  0.063811  0.419110  0.227827
40  0.182994  0.263806   0.0  0.030000  0.0  0.037531  0.190320  0.081459
60  0.198889  0.189048   0.0  0.058284  0.0  0.037645  0.268203  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  0.765543  0.425937  0.033380  0.0  0.083726  0.014248
10  0.0  0.206570  ...  0.791185  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.066103  ...  0.678759  0.059940  0.018495  0.0  0.061583  0.031034
40  0.0  0.080508  ...  0.950124  0.051065  0.030664  0.0  0.049047  0.045574
60  0.0  0.074836  ...  0.943136  0.055703  0.030099  0.0  0.047652  0.021674

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.052006
10  0.0  0.018880  0.0  0.038203
20  0.0  0.009014  0.0  0.056665
40  0.0  0.007993  0.0  0.037330
60  0.0  0.008053  0.0  0.042037

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     60
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA     5
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     20
ABT     60
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA     5
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-04-07
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-10:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.314455   0.0  0.763110  0.0  0.053964  0.752132  0.085090
10  0.237439  0.340327   0.0  0.044857  0.0  0.069162  0.431763  0.119554
20  0.219027  0.334404   0.0  0.077315  0.0  0.063811  0.419110  0.227827
40  0.182994  0.263806   0.0  0.056540  0.0  0.132909  0.190320  0.081845
60  0.198889  0.308110   0.0  0.058284  0.0  0.037645  0.268203  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  0.765543  0.425937  0.033380  0.0  0.083726  0.162268
10  0.0  0.206570  ...  0.791185  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.077021  ...  0.994681  0.059940  0.018535  0.0  0.061583  0.031034
40  0.0  0.080508  ...  0.950124  0.062769  0.030664  0.0  0.049047  0.045574
60  0.0  0.074836  ...  0.943136  0.055703  0.030099  0.0  0.053337  0.021674

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.052006
10  0.0  0.018880  0.0  0.038203
20  0.0  0.009014  0.0  0.056665
40  0.0  0.010790  0.0  0.057337
60  0.0  0.008053  0.0  0.042037

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    10
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-04-10
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-11:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.314455   0.0  0.763110  0.0  0.053964  0.752132  0.085090
10  0.237439  0.340327   0.0  0.618837  0.0  0.069162  0.431763  0.119554
20  0.219027  0.334404   0.0  0.077315  0.0  0.063811  0.419110  0.227827
40  0.240493  0.347597   0.0  0.056540  0.0  0.132909  0.289398  0.082077
60  0.198889  0.308110   0.0  0.058284  0.0  0.063956  0.268203  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.357434  0.425937  0.033380  0.0  0.083726  0.162268
10  0.0  0.206570  ...  0.791185  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.077021  ...  0.994681  0.059940  0.018792  0.0  0.061583  0.031034
40  0.0  0.080508  ...  0.950124  0.062769  0.030664  0.0  0.049047  0.045574
60  0.0  0.109541  ...  0.943136  0.074873  0.030099  0.0  0.053337  0.025481

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.052006
10  0.0  0.018880  0.0  0.059211
20  0.0  0.009014  0.0  0.056665
40  0.0  0.010790  0.0  0.057337
60  0.0  0.008400  0.0  0.042037

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-04-11
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-12:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.314455   0.0  0.763110  0.0  5.668286  0.752132  0.085090
10  0.237439  0.340327   0.0  0.618837  0.0  0.069162  0.431763  0.119554
20  0.219027  0.334404   0.0  0.077315  0.0  0.063811  0.419110  0.227827
40  0.240493  0.347597   0.0  0.076388  0.0  0.132909  0.289398  0.082565
60  0.252135  0.401978   0.0  0.058284  0.0  0.063956  0.362749  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.357434  0.425937  0.033380  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.369466  0.061620  0.020995  0.0  0.079745  0.092313
20  0.0  0.109937  ...  0.994681  0.085387  0.022012  0.0  0.061583  0.031034
40  0.0  0.080508  ...  0.950124  0.062769  0.030664  0.0  0.049432  0.045574
60  0.0  0.109541  ...  0.943136  0.074873  0.030099  0.0  0.053337  0.025512

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.052006
10  0.0  0.018880  0.0  0.059211
20  0.0  0.009014  0.0  0.056665
40  0.0  0.010790  0.0  0.057337
60  0.0  0.008470  0.0  0.061370

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT      5
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     20
ABT      5
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-04-12
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-04-13:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.529421   0.0  0.763110  0.0  5.668286  0.752132  0.085090
10  0.237439  0.340327   0.0  0.618837  0.0  0.069162  0.431763  0.119554
20  0.292234  0.334404   0.0  0.077315  0.0  0.075791  0.419110  0.227827
40  0.240493  0.347597   0.0  0.076388  0.0  0.132909  0.401800  0.082948
60  0.252135  0.401978   0.0  0.120601  0.0  0.063956  0.362749  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.357434  0.425937  0.033380  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.369466  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.109937  ...  0.994681  0.085387  0.022012  0.0  0.061583  0.031034
40  0.0  0.120773  ...  0.950124  0.062769  0.030664  0.0  0.049905  0.045574
60  0.0  0.109541  ...  1.258602  0.074873  0.030099  0.0  0.053337  0.025728

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.077408
10  0.0  0.018880  0.0  0.059211
20  0.0  0.009014  0.0  0.056665
40  0.0  0.010790  0.0  0.057337
60  0.0  0.011114  0.0  0.061370

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     20
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     10
ABT     20
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-04-13
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-14:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.529421   0.0  0.763110  0.0  5.668286  0.752132  0.085090
10  0.344931  0.340327   0.0  0.618837  0.0  0.069162  0.431763  0.119554
20  0.292234  0.604989   0.0  0.077315  0.0  0.075791  0.419110  0.227827
40  0.240493  0.347597   0.0  0.076803  0.0  0.132909  0.401800  0.091226
60  0.252135  0.401978   0.0  0.120601  0.0  0.075809  0.451082  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.357434  0.425937  0.033380  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.369466  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.109937  ...  0.994681  0.085387  0.037285  0.0  0.061583  0.031034
40  0.0  0.120773  ...  1.245260  0.082968  0.030664  0.0  0.052096  0.045574
60  0.0  0.153157  ...  1.258602  0.074873  0.030099  0.0  0.053337  0.025890

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.077408
10  0.0  0.018880  0.0  0.059211
20  0.0  0.011987  0.0  0.080912
40  0.0  0.010790  0.0  0.057337
60  0.0  0.011114  0.0  0.061370

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     10
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     40
ABT     10
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-04-14
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-17:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.529421   0.0  0.763110  0.0  5.668286  0.752132  0.085522
10  0.344931  0.451437   0.0  0.618837  0.0  0.187910  0.431763  0.119554
20  0.292234  0.604989   0.0  0.077315  0.0  0.075791  0.419110  0.227827
40  0.319965  0.347597   0.0  0.082166  0.0  0.132909  0.548470  0.091226
60  0.252135  0.401978   0.0  0.120601  0.0  0.075809  0.451082  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.357434  0.425937  0.033380  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.369466  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.155116  ...  1.391058  0.085387  0.037285  0.0  0.061583  0.031034
40  0.0  0.120773  ...  1.245260  0.082968  0.030664  0.0  0.053381  0.045574
60  0.0  0.153157  ...  1.258602  0.102113  0.039521  0.0  0.053337  0.026033

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.077408
10  0.0  0.018880  0.0  0.059211
20  0.0  0.011987  0.0  0.080912
40  0.0  0.019998  0.0  0.087074
60  0.0  0.011114  0.0  0.061370

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     40
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     60
ABT     40
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-04-17
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-18:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.252377  0.529421   0.0  0.763110  0.0  5.668286  0.752132  0.356380
10  0.344931  0.451437   0.0  0.618837  0.0  0.187910  0.431763  0.119554
20  0.292234  0.604989   0.0  0.132954  0.0  0.084772  1.115880  0.227827
40  0.319965  0.439451   0.0  0.082166  0.0  0.132909  0.548470  0.091226
60  0.325127  0.401978   0.0  0.120601  0.0  0.075809  0.451082  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.357434  0.425937  0.033380  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.369466  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.155116  ...  1.391058  0.085387  0.037285  0.0  0.061583  0.031034
40  0.0  0.151376  ...  1.578608  0.095430  0.094558  0.0  0.053381  0.045574
60  0.0  0.153157  ...  1.258602  0.102113  0.039521  0.0  0.058063  0.037900

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.077408
10  0.0  0.018880  0.0  0.071963
20  0.0  0.011987  0.0  0.080912
40  0.0  0.019998  0.0  0.087074
60  0.0  0.021020  0.0  0.061370

[5 rows x 506 columns]
W.idxmin(): MMM      5
ABT     60
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM      5
ABT     60
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    20
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-04-18
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-19:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.371977  0.529421   0.0  0.763110  0.0  5.668286  0.752132  0.356380
10  0.344931  0.451437   0.0  0.618837  0.0  0.187910  0.894746  0.119554
20  0.292234  0.604989   0.0  0.132954  0.0  0.084772  1.115880  0.227827
40  0.319965  0.439451   0.0  0.139112  0.0  0.132909  0.548470  0.161409
60  0.325127  0.500078   0.0  0.120601  0.0  0.080927  0.451082  0.106480

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.357434  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.369466  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.155116  ...  1.391058  0.163176  0.037285  0.0  0.061583  0.097729
40  0.0  0.169136  ...  1.578608  0.095430  0.094558  0.0  0.056214  0.045574
60  0.0  0.153157  ...  1.577871  0.102113  0.039521  0.0  0.058063  0.037900

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.077408
10  0.0  0.018880  0.0  0.071963
20  0.0  0.066445  0.0  0.080912
40  0.0  0.019998  0.0  0.087074
60  0.0  0.021020  0.0  0.076255

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     20
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    10
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-04-19
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-04-20:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.371977  0.529421   0.0  0.763110  0.0  5.668286  0.752132  0.356380
10  0.344931  0.451437   0.0  0.618837  0.0  0.187910  0.894746  0.119554
20  0.400463  0.604989   0.0  0.132954  0.0  0.084772  1.115880  0.227827
40  0.319965  0.538393   0.0  0.139112  0.0  0.132909  0.548470  0.161409
60  0.325127  0.500078   0.0  0.129191  0.0  0.095158  0.585175  0.126259

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.726824  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.369466  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.155116  ...  1.391058  0.163176  0.097704  0.0  0.061583  0.097729
40  0.0  0.169136  ...  1.578608  0.115606  0.094558  0.0  0.060336  0.045574
60  0.0  0.182122  ...  1.577871  0.102113  0.039521  0.0  0.058063  0.038361

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.077408
10  0.0  0.101911  0.0  0.093675
20  0.0  0.066445  0.0  0.080912
40  0.0  0.019998  0.0  0.087074
60  0.0  0.021020  0.0  0.076255

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     10
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     40
ABT     10
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-04-20
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-24:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.371977  0.529421   0.0  0.763110  0.0  5.668286  0.752132  0.356380
10  0.344931  0.534593   0.0  0.618837  0.0  0.187910  0.894746  0.360829
20  0.400463  0.604989   0.0  0.132954  0.0  0.085580  1.115880  0.227827
40  0.397553  0.538393   0.0  0.139112  0.0  0.132909  0.911574  0.161409
60  0.325127  0.500078   0.0  0.135064  0.0  0.095158  0.585175  0.126259

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.726824  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.706870  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.164815  ...  1.391058  0.163176  0.097704  0.0  0.061583  0.097729
40  0.0  0.169136  ...  1.578608  0.115606  0.094558  0.0  0.060336  0.045574
60  0.0  0.182122  ...  1.577871  0.127365  0.044028  0.0  0.058373  0.095430

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.077408
10  0.0  0.101911  0.0  0.093675
20  0.0  0.066445  0.0  0.080912
40  0.0  0.026784  0.0  0.087074
60  0.0  0.021020  0.0  0.095771

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-04-24
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-25:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.371977  0.529421   0.0  0.763110  0.0  5.668286  0.752132  0.356380
10  0.344931  0.534593   0.0  0.618837  0.0  0.187910  0.894746  0.360829
20  0.400463  0.604989   0.0  0.234675  0.0  0.088754  1.115880  0.227827
40  0.397553  0.538393   0.0  0.139112  0.0  0.132909  0.911574  0.161409
60  0.380837  0.585348   0.0  0.135064  0.0  0.095158  0.719237  0.179068

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.726824  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.706870  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.196890  ...  1.735251  0.163176  0.097704  0.0  0.061583  0.097729
40  0.0  0.169136  ...  1.578608  0.150456  0.094558  0.0  0.060336  0.055188
60  0.0  0.182122  ...  1.577871  0.127365  0.046845  0.0  0.059655  0.095430

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.096254
10  0.0  0.101911  0.0  0.093675
20  0.0  0.066445  0.0  0.080912
40  0.0  0.026784  0.0  0.087074
60  0.0  0.027686  0.0  0.095771

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT      5
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     10
ABT      5
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-04-25
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-26:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.371977  0.697195   0.0  0.763110  0.0  5.668286  0.752132  0.356380
10  0.477636  0.534593   0.0  0.618837  0.0  0.187910  0.894746  0.360829
20  0.400463  0.604989   0.0  0.234675  0.0  0.090645  1.115880  0.227827
40  0.397553  0.538393   0.0  0.139112  0.0  0.132909  0.911574  0.264741
60  0.380837  0.585348   0.0  0.142361  0.0  0.095158  1.002909  0.179068

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.726824  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.706870  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.196890  ...  1.735251  0.163176  0.097704  0.0  0.061583  0.097729
40  0.0  0.199361  ...  1.578608  0.150456  0.094558  0.0  0.060336  0.073317
60  0.0  0.182122  ...  1.873286  0.146100  0.065793  0.0  0.067484  0.095430

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.096254
10  0.0  0.101911  0.0  0.093675
20  0.0  0.066445  0.0  0.096361
40  0.0  0.036859  0.0  0.087074
60  0.0  0.027686  0.0  0.095771

[5 rows x 506 columns]
W.idxmin(): MMM      5
ABT     10
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    60
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM      5
ABT     10
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    60
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-04-26
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-04-27:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.536570  0.697195   0.0  0.763110  0.0  5.668286  1.909210  0.356380
10  0.477636  0.627637   0.0  0.618837  0.0  0.187910  0.894746  0.360829
20  0.400463  0.604989   0.0  0.234675  0.0  0.091591  1.115880  0.227827
40  0.397553  0.538393   0.0  0.199367  0.0  0.132909  0.911574  0.264741
60  0.380837  0.585348   0.0  0.142361  0.0  0.095158  1.002909  0.201952

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.726824  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.206570  ...  1.706870  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.196890  ...  1.735251  0.163176  0.097704  0.0  0.061583  0.097729
40  0.0  0.199361  ...  1.891625  0.150456  0.094558  0.0  0.061101  0.075114
60  0.0  0.210328  ...  1.873286  0.160514  0.066695  0.0  0.067484  0.095430

    ZBH      ZION  ZTS       SPY
5   0.0  0.032282  0.0  0.096254
10  0.0  0.101911  0.0  0.093675
20  0.0  0.066445  0.0  0.096361
40  0.0  0.036859  0.0  0.108889
60  0.0  0.044807  0.0  0.095771

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION     5
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     60
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION     5
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-04-27
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-04-28:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.536570  0.697195   0.0  0.763110  0.0  5.668286  1.909210  0.356380
10  0.477636  0.627637   0.0  0.618837  0.0  0.187910  1.673824  0.360829
20  0.400463  0.604989   0.0  0.234675  0.0  0.093136  1.115880  0.227827
40  0.397553  0.631808   0.0  0.199367  0.0  0.132909  0.911574  0.264741
60  0.469341  0.585348   0.0  0.150569  0.0  0.095158  1.002909  0.267904

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  1.726824  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.206570  ...  2.053395  0.177133  0.115774  0.0  0.079745  0.092313
20  0.0  0.235282  ...  1.735251  0.163176  0.097704  0.0  0.061583  0.097729
40  0.0  0.199361  ...  1.891625  0.188855  0.094558  0.0  0.061102  0.110588
60  0.0  0.210328  ...  1.873286  0.160514  0.111417  0.0  0.067484  0.095430

    ZBH      ZION  ZTS       SPY
5   0.0  0.058525  0.0  0.096254
10  0.0  0.101911  0.0  0.109710
20  0.0  0.066445  0.0  0.096361
40  0.0  0.036859  0.0  0.108889
60  0.0  0.044807  0.0  0.095771

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    40
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     40
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    40
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-04-28
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-01:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.536570  0.697195   0.0  0.763110  0.0  5.668286  1.909210  0.356380
10  0.477636  0.627637   0.0  0.618837  0.0  0.187910  1.673824  0.360829
20  0.400463  0.604989   0.0  0.234675  0.0  0.093508  1.115880  0.457183
40  0.492005  0.631808   0.0  0.199367  0.0  0.132909  1.318242  0.264741
60  0.469341  0.685180   0.0  0.167297  0.0  0.095158  1.002909  0.267904

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  2.035752  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.206570  ...  2.053395  0.177133  0.115774  0.0  0.079745  0.185635
20  0.0  0.235282  ...  1.735251  0.163176  0.097704  0.0  0.061583  0.097729
40  0.0  0.218000  ...  1.891625  0.188855  0.134687  0.0  0.066678  0.110588
60  0.0  0.210328  ...  1.873286  0.198941  0.111417  0.0  0.067484  0.095430

    ZBH      ZION  ZTS       SPY
5   0.0  0.058525  0.0  0.096254
10  0.0  0.101911  0.0  0.109710
20  0.0  0.066445  0.0  0.096361
40  0.0  0.053271  0.0  0.108889
60  0.0  0.044807  0.0  0.118180

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-05-01
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-02:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.536570  0.697195   0.0  0.763110  0.0  5.668286  1.909210  0.356380
10  0.477636  0.627637   0.0  0.618837  0.0  0.187910  1.673824  0.360829
20  0.522878  0.714455   0.0  0.234675  0.0  0.095447  1.115880  0.457183
40  0.492005  0.631808   0.0  0.199367  0.0  0.132909  1.318242  0.345141
60  0.469341  0.685180   0.0  0.167738  0.0  0.095158  1.316287  0.267904

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  2.035752  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.360758  ...  2.053395  0.177133  0.115774  0.0  0.079745  0.185635
20  0.0  0.235282  ...  2.056506  0.215610  0.206856  0.0  0.074229  0.097729
40  0.0  0.218000  ...  1.891625  0.188855  0.134687  0.0  0.066678  0.110588
60  0.0  0.210328  ...  1.873286  0.198941  0.111417  0.0  0.067484  0.124941

    ZBH      ZION  ZTS       SPY
5   0.0  0.058525  0.0  0.115455
10  0.0  0.101911  0.0  0.109710
20  0.0  0.066445  0.0  0.096361
40  0.0  0.053271  0.0  0.108889
60  0.0  0.054928  0.0  0.118180

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     10
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     60
ABT     10
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-05-02
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-03:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.536570  0.697195   0.0  0.763110  0.0  5.668286  1.909210  0.356380
10  0.477636  0.757922   0.0  0.618837  0.0  0.187910  1.673824  0.360829
20  0.522878  0.714455   0.0  0.234675  0.0  0.095447  1.625141  0.457183
40  0.492005  0.631808   0.0  0.199367  0.0  0.132909  1.318242  0.345141
60  0.550527  0.685180   0.0  0.168873  0.0  0.095339  1.316287  0.307416

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  2.035752  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.360758  ...  2.053395  0.306598  0.115774  0.0  0.079745  0.185635
20  0.0  0.235282  ...  2.056506  0.215610  0.206856  0.0  0.074229  0.180582
40  0.0  0.218000  ...  1.891625  0.188855  0.134687  0.0  0.067481  0.110588
60  0.0  0.264056  ...  2.189319  0.198941  0.113501  0.0  0.067484  0.124941

    ZBH      ZION  ZTS       SPY
5   0.0  0.058525  0.0  0.115455
10  0.0  0.101911  0.0  0.109710
20  0.0  0.066445  0.0  0.118060
40  0.0  0.062071  0.0  0.108889
60  0.0  0.054928  0.0  0.118180

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    60
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     10
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    60
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-05-03
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-04:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.536570  0.697195   0.0  0.763110  0.0  5.668286  1.909210  0.356380
10  0.632086  0.757922   0.0  0.618837  0.0  0.187910  1.673824  0.360829
20  0.522878  0.714455   0.0  0.234675  0.0  0.095447  1.625141  0.457183
40  0.492005  0.749070   0.0  0.199367  0.0  0.132909  1.318242  0.345141
60  0.550527  0.685180   0.0  0.172814  0.0  0.096199  1.551447  0.337335

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  2.035752  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.360758  ...  2.053395  0.306598  0.115774  0.0  0.079745  0.185635
20  0.0  0.235282  ...  2.056506  0.215610  0.206856  0.0  0.074229  0.180582
40  0.0  0.258058  ...  2.226240  0.223192  0.134687  0.0  0.069319  0.131290
60  0.0  0.264056  ...  2.189319  0.198941  0.122682  0.0  0.067484  0.124941

    ZBH      ZION  ZTS       SPY
5   0.0  0.058525  0.0  0.115455
10  0.0  0.101911  0.0  0.109710
20  0.0  0.066445  0.0  0.118060
40  0.0  0.062071  0.0  0.133293
60  0.0  0.075246  0.0  0.118180

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION     5
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     40
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION     5
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-05-04
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-05-05:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.536570  0.697195   0.0  0.763110  0.0  5.668286  1.909210  0.356380
10  0.632086  0.757922   0.0  0.618837  0.0  0.187910  1.673824  0.360829
20  0.522878  0.714455   0.0  0.234675  0.0  0.098574  1.625141  0.457183
40  0.599544  0.749070   0.0  0.199367  0.0  0.132909  1.757077  0.345141
60  0.550527  0.784277   0.0  0.201519  0.0  0.096199  1.551447  0.383722

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  2.287761  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.360758  ...  2.053395  0.306598  0.206039  0.0  0.079745  0.185635
20  0.0  0.279893  ...  2.056506  0.215610  0.206856  0.0  0.074229  0.180582
40  0.0  0.258058  ...  2.226240  0.223192  0.134687  0.0  0.069319  0.131290
60  0.0  0.264056  ...  2.189319  0.228441  0.122682  0.0  0.081634  0.149303

    ZBH      ZION  ZTS       SPY
5   0.0  0.065142  0.0  0.115455
10  0.0  0.101911  0.0  0.129812
20  0.0  0.066445  0.0  0.118060
40  0.0  0.062071  0.0  0.133293
60  0.0  0.075246  0.0  0.118180

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT      5
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     20
ABT      5
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    40
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-05-05
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-08:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.536570  0.769089   0.0  0.763110  0.0  5.668286  1.909210  0.356380
10  0.632086  0.757922   0.0  0.618837  0.0  0.187910  1.673824  0.360829
20  0.635523  0.714455   0.0  0.234675  0.0  0.098574  1.625141  0.457183
40  0.599544  0.749070   0.0  0.286281  0.0  0.132909  1.757077  0.455017
60  0.550527  0.784277   0.0  0.201519  0.0  0.100279  1.934219  0.383722

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  2.287761  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.360758  ...  2.379738  0.306598  0.206039  0.0  0.079745  0.185635
20  0.0  0.279893  ...  2.056506  0.254574  0.206856  0.0  0.074229  0.180582
40  0.0  0.287932  ...  2.226240  0.223192  0.134687  0.0  0.069805  0.170326
60  0.0  0.264056  ...  2.189319  0.228441  0.138788  0.0  0.081634  0.149303

    ZBH      ZION  ZTS       SPY
5   0.0  0.065142  0.0  0.132094
10  0.0  0.101911  0.0  0.129812
20  0.0  0.066445  0.0  0.118060
40  0.0  0.071904  0.0  0.133293
60  0.0  0.075246  0.0  0.118180

[5 rows x 506 columns]
W.idxmin(): MMM      5
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION     5
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM      5
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION     5
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-05-08
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-09:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.634065  0.769089   0.0  0.763110  0.0  5.668286  1.909210  0.406850
10  0.632086  0.757922   0.0  0.618837  0.0  0.187910  1.673824  0.360829
20  0.635523  0.801620   0.0  0.234675  0.0  0.102087  2.137589  0.457183
40  0.599544  0.749070   0.0  0.286281  0.0  0.132909  1.757077  0.455017
60  0.550527  0.784277   0.0  0.211645  0.0  0.100279  1.934219  0.383722

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  2.287761  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.360758  ...  2.379738  0.306598  0.206039  0.0  0.079745  0.185635
20  0.0  0.279893  ...  2.388825  0.254574  0.206856  0.0  0.074229  0.180582
40  0.0  0.287932  ...  2.226240  0.253003  0.171147  0.0  0.072643  0.170326
60  0.0  0.317220  ...  2.189319  0.228441  0.138788  0.0  0.081634  0.158194

    ZBH      ZION  ZTS       SPY
5   0.0  0.065369  0.0  0.132094
10  0.0  0.101911  0.0  0.129812
20  0.0  0.066445  0.0  0.138308
40  0.0  0.071904  0.0  0.133293
60  0.0  0.075246  0.0  0.118180

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION     5
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION     5
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-05-09
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-10:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.634065  0.769089   0.0  0.763110  0.0  5.668286  1.909210  0.406850
10  0.632086  0.757922   0.0  0.618837  0.0  0.187910  2.808797  0.509076
20  0.635523  0.801620   0.0  0.234675  0.0  0.102087  2.137589  0.457183
40  0.599544  0.859527   0.0  0.286281  0.0  0.132909  1.757077  0.455017
60  0.642298  0.784277   0.0  0.213479  0.0  0.100642  1.934219  0.383722

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  2.287761  0.425937  0.148585  0.0  0.083726  0.162268
10  0.0  0.360758  ...  2.379738  0.306598  0.206039  0.0  0.079745  0.185635
20  0.0  0.325095  ...  2.388825  0.254574  0.206856  0.0  0.074229  0.180582
40  0.0  0.287932  ...  2.226240  0.253003  0.171147  0.0  0.073851  0.170326
60  0.0  0.317220  ...  2.507318  0.259172  0.143846  0.0  0.081634  0.175532

    ZBH      ZION  ZTS       SPY
5   0.0  0.065684  0.0  0.132094
10  0.0  0.101911  0.0  0.129812
20  0.0  0.066445  0.0  0.138308
40  0.0  0.071904  0.0  0.133293
60  0.0  0.075246  0.0  0.140439

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     10
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA     5
ZBH      5
ZION     5
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     40
ABT     10
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA     5
ZBH      5
ZION     5
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-05-10
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-11:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.634065  0.769089   0.0  0.763110  0.0  5.668286  1.909210  0.406850
10  0.632086  0.858348   0.0  0.618837  0.0  0.187910  2.808797  0.509076
20  0.635523  0.801620   0.0  0.234675  0.0  0.102087  2.137589  0.457183
40  0.698503  0.859527   0.0  0.286281  0.0  0.132909  2.208057  0.455017
60  0.642298  0.784277   0.0  0.217152  0.0  0.103114  1.934219  0.435864

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.304609  ...  2.287761  0.425937  0.148585  0.0  0.083726  0.502849
10  0.0  0.360758  ...  2.379738  0.306598  0.206039  0.0  0.079745  0.185635
20  0.0  0.325095  ...  2.388825  0.254574  0.206856  0.0  0.074229  0.180582
40  0.0  0.332429  ...  2.555207  0.296876  0.171147  0.0  0.076192  0.170326
60  0.0  0.317220  ...  2.507318  0.259172  0.146969  0.0  0.081634  0.175532

    ZBH      ZION  ZTS       SPY
5   0.0  0.075409  0.0  0.132094
10  0.0  0.101911  0.0  0.153028
20  0.0  0.066445  0.0  0.138308
40  0.0  0.071904  0.0  0.133293
60  0.0  0.075246  0.0  0.140439

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT      5
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    20
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     10
ABT      5
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    20
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-05-11
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-05-12:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.634065  0.959663   0.0  0.763110  0.0  5.668286  2.184336  0.872812
10  0.740078  0.858348   0.0  0.618837  0.0  0.187910  2.808797  0.509076
20  0.635523  0.801620   0.0  0.234675  0.0  0.122331  2.137589  0.457183
40  0.698503  0.859527   0.0  0.286281  0.0  0.132909  2.208057  0.455017
60  0.642298  0.784277   0.0  0.223411  0.0  0.103114  1.934219  0.435864

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.327184  ...  2.671769  0.425937  0.148585  0.0  0.083726  0.502849
10  0.0  0.360758  ...  2.379738  0.306598  0.206039  0.0  0.079745  0.185635
20  0.0  0.325095  ...  2.388825  0.335281  0.206856  0.0  0.081325  0.180582
40  0.0  0.332429  ...  2.555207  0.296876  0.171147  0.0  0.076192  0.261921
60  0.0  0.317220  ...  2.507318  0.259172  0.168329  0.0  0.081634  0.175532

    ZBH      ZION  ZTS       SPY
5   0.0  0.075409  0.0  0.150394
10  0.0  0.101911  0.0  0.153028
20  0.0  0.089245  0.0  0.138308
40  0.0  0.071904  0.0  0.133293
60  0.0  0.075246  0.0  0.140439

[5 rows x 506 columns]
W.idxmin(): MMM      5
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM      5
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-05-12
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-15:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.788311  0.959663   0.0  0.763110  0.0  5.668286  2.184336  0.872812
10  0.740078  0.858348   0.0  0.618837  0.0  0.187910  2.808797  0.509076
20  0.635523  0.801620   0.0  0.234675  0.0  0.122331  2.137589  0.457183
40  0.698503  0.859527   0.0  0.286281  0.0  0.132909  2.208057  0.455017
60  0.642298  0.887407   0.0  0.228116  0.0  0.106557  2.274135  0.487457

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.327184  ...  2.671769  0.425937  0.260231  0.0  0.083726  0.502849
10  0.0  0.360758  ...  2.748960  0.306598  0.206039  0.0  0.079745  0.185635
20  0.0  0.325095  ...  2.388825  0.335281  0.206856  0.0  0.081325  0.180582
40  0.0  0.332429  ...  2.555207  0.296876  0.171147  0.0  0.107582  0.261921
60  0.0  0.337876  ...  2.507318  0.281949  0.168329  0.0  0.081634  0.221628

    ZBH      ZION  ZTS       SPY
5   0.0  0.075409  0.0  0.150394
10  0.0  0.101911  0.0  0.153028
20  0.0  0.089245  0.0  0.138308
40  0.0  0.083722  0.0  0.151814
60  0.0  0.075246  0.0  0.140439

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    60
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    60
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-05-15
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-16:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.788311  0.959663   0.0  0.763110  0.0  5.668286  2.184336  0.872812
10  0.740078  0.858348   0.0  0.618837  0.0  0.187910  2.808797  0.509076
20  0.772559  0.905857   0.0  0.234675  0.0  0.122331  2.754940  0.457183
40  0.698503  0.859527   0.0  0.286281  0.0  0.132909  2.208057  0.564983
60  0.642298  0.887407   0.0  0.248736  0.0  0.110989  2.274135  0.487457

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.327184  ...  2.671769  0.425937  0.260231  0.0  0.083726  0.502849
10  0.0  0.360758  ...  2.748960  0.306598  0.206039  0.0  0.148340  0.185635
20  0.0  0.337754  ...  2.730166  0.335281  0.206856  0.0  0.081325  0.323533
40  0.0  0.332429  ...  2.555207  0.296876  0.171147  0.0  0.107582  0.261921
60  0.0  0.337876  ...  2.507318  0.319279  0.205498  0.0  0.081634  0.221628

    ZBH      ZION  ZTS       SPY
5   0.0  0.075409  0.0  0.150394
10  0.0  0.101911  0.0  0.153028
20  0.0  0.089245  0.0  0.154907
40  0.0  0.083722  0.0  0.151814
60  0.0  0.083003  0.0  0.140439

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     10
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    10
ZBH      5
ZION     5
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     60
ABT     10
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    10
ZBH      5
ZION     5
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-05-16
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-17:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.788311  0.959663   0.0  0.763110  0.0  5.668286  2.234285  0.872812
10  0.740078  0.968322   0.0  0.618837  0.0  0.187910  2.808797  0.509076
20  0.772559  0.905857   0.0  0.250715  0.0  0.122331  2.754940  0.737961
40  0.698503  0.859527   0.0  0.286281  0.0  0.132909  2.208057  0.564983
60  0.721026  0.887407   0.0  0.248736  0.0  0.110998  2.274135  0.487457

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  2.671769  0.425937  0.260231  0.0  0.083726  0.502849
10  0.0  0.360758  ...  2.748960  0.306598  0.206039  0.0  0.148340  0.238085
20  0.0  0.337754  ...  2.730166  0.335281  0.206856  0.0  0.093061  0.323533
40  0.0  0.332429  ...  2.555207  0.337230  0.264295  0.0  0.107582  0.261921
60  0.0  0.337876  ...  2.834740  0.319279  0.205498  0.0  0.081634  0.221628

    ZBH      ZION  ZTS       SPY
5   0.0  0.080963  0.0  0.150394
10  0.0  0.101911  0.0  0.153028
20  0.0  0.089245  0.0  0.154907
40  0.0  0.083722  0.0  0.151814
60  0.0  0.083003  0.0  0.160124

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION     5
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION     5
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-05-17
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-18:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.788311  0.959663   0.0  0.763110  0.0  5.668286  2.234285  0.872812
10  0.740078  0.968322   0.0  0.618837  0.0  0.187910  2.808797  0.509076
20  0.772559  0.905857   0.0  0.250715  0.0  0.122331  2.754940  0.737961
40  0.815910  0.975358   0.0  0.286281  0.0  0.132909  2.706032  0.564983
60  0.721026  0.887407   0.0  0.268946  0.0  0.111637  2.274135  0.532702

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  2.671769  0.425937  0.260231  0.0  0.083726  0.502849
10  0.0  0.360758  ...  2.748960  0.380278  0.206039  0.0  0.148340  0.238085
20  0.0  0.337754  ...  2.730166  0.335281  0.206856  0.0  0.093061  0.323533
40  0.0  0.350393  ...  2.907775  0.337230  0.264295  0.0  0.107582  0.261921
60  0.0  0.337876  ...  2.834740  0.319279  0.235370  0.0  0.085640  0.242467

    ZBH      ZION  ZTS       SPY
5   0.0  0.081087  0.0  0.170946
10  0.0  0.101911  0.0  0.153028
20  0.0  0.089245  0.0  0.154907
40  0.0  0.083722  0.0  0.151814
60  0.0  0.083003  0.0  0.160124

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    10
ZBH      5
ZION     5
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    10
ZBH      5
ZION     5
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-05-18
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-05-19:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.788311  0.959663   0.0  0.763110  0.0  5.668286  2.291203  0.872812
10  0.740078  0.968322   0.0  0.618837  0.0  0.187910  2.808797  0.622951
20  0.772559  0.905857   0.0  0.274723  0.0  0.122331  2.754940  0.737961
40  0.815910  0.975358   0.0  0.286281  0.0  0.132909  2.706032  0.564983
60  0.817628  0.979909   0.0  0.268946  0.0  0.111890  2.274135  0.532702

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.031577  0.425937  0.260231  0.0  0.258106  0.502849
10  0.0  0.360758  ...  2.748960  0.380278  0.301885  0.0  0.148340  0.353260
20  0.0  0.358445  ...  2.730166  0.335281  0.206856  0.0  0.093061  0.323533
40  0.0  0.350393  ...  2.907775  0.337230  0.264295  0.0  0.107582  0.261921
60  0.0  0.337876  ...  2.834740  0.354779  0.235370  0.0  0.085640  0.242467

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.170946
10  0.0  0.101911  0.0  0.153028
20  0.0  0.089245  0.0  0.154907
40  0.0  0.083722  0.0  0.174730
60  0.0  0.083003  0.0  0.160124

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     10
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-05-19
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-22:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.788311  0.959663   0.0  0.763110  0.0  5.668286  2.291203  0.872812
10  0.856708  0.968322   0.0  0.618837  0.0  0.187910  2.808797  0.622951
20  0.772559  1.043817   0.0  0.274723  0.0  0.122331  2.754940  0.737961
40  0.815910  0.975358   0.0  0.286281  0.0  0.132909  2.706032  0.564983
60  0.817628  0.979909   0.0  0.296713  0.0  0.114946  2.655133  0.593791

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.031577  0.425937  0.260231  0.0  0.258106  0.502849
10  0.0  0.360758  ...  2.748960  0.380278  0.301885  0.0  0.148340  0.353260
20  0.0  0.358445  ...  3.061052  0.399158  0.290043  0.0  0.093061  0.323533
40  0.0  0.350393  ...  2.907775  0.337230  0.264295  0.0  0.107582  0.261921
60  0.0  0.361015  ...  2.834740  0.354779  0.235370  0.0  0.096775  0.255812

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.170946
10  0.0  0.101911  0.0  0.174853
20  0.0  0.089245  0.0  0.154907
40  0.0  0.083722  0.0  0.174730
60  0.0  0.094540  0.0  0.160124

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT      5
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     20
ABT      5
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-05-22
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-23:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.788311  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.856708  0.968322   0.0  0.618837  0.0  0.187910  2.808797  0.622951
20  0.912901  1.043817   0.0  0.288742  0.0  0.122331  2.754940  0.737961
40  0.815910  0.975358   0.0  0.286281  0.0  0.132909  2.706032  0.710380
60  0.817628  0.979909   0.0  0.296713  0.0  0.118030  2.655133  0.593791

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.031577  0.425937  0.260231  0.0  0.258106  0.502849
10  0.0  0.360758  ...  3.119041  0.380278  0.301885  0.0  0.148340  0.353260
20  0.0  0.358445  ...  3.061052  0.399158  0.290043  0.0  0.108559  0.323533
40  0.0  0.373159  ...  2.907775  0.392822  0.264295  0.0  0.107582  0.261921
60  0.0  0.361015  ...  2.834740  0.354779  0.286994  0.0  0.096775  0.295909

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.170946
10  0.0  0.101911  0.0  0.174853
20  0.0  0.089245  0.0  0.176397
40  0.0  0.114785  0.0  0.174730
60  0.0  0.094540  0.0  0.160124

[5 rows x 506 columns]
W.idxmin(): MMM      5
ABT     10
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    20
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM      5
ABT     10
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    20
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-05-23
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-24:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.955574  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.856708  1.171461   0.0  0.618837  0.0  0.187910  2.808797  0.622951
20  0.912901  1.043817   0.0  0.288742  0.0  0.122331  2.754940  0.737961
40  0.815910  0.975358   0.0  0.349974  0.0  0.132909  2.706032  0.710380
60  0.817628  0.979909   0.0  0.296713  0.0  0.119255  3.075938  0.658776

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.031577  0.425937  0.910756  0.0  0.258106  0.502849
10  0.0  0.360758  ...  3.119041  0.380278  0.301885  0.0  0.148340  0.353260
20  0.0  0.372830  ...  3.061052  0.399158  0.290043  0.0  0.108559  0.323533
40  0.0  0.373159  ...  2.907775  0.392822  0.264295  0.0  0.107582  0.345735
60  0.0  0.361015  ...  3.171247  0.390550  0.286994  0.0  0.098817  0.295909

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.170946
10  0.0  0.101911  0.0  0.174853
20  0.0  0.115700  0.0  0.176397
40  0.0  0.114785  0.0  0.174730
60  0.0  0.094540  0.0  0.183434

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     40
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     40
ABT     40
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-05-24
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-25:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.955574  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.856708  1.171461   0.0  0.618837  0.0  0.187910  2.808797  0.710107
20  0.912901  1.043817   0.0  0.355543  0.0  0.122331  2.754940  0.737961
40  0.916273  1.090748   0.0  0.349974  0.0  0.132909  3.143382  0.710380
60  0.817628  0.979909   0.0  0.296713  0.0  0.122308  3.075938  0.658776

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.031577  0.425937  0.910756  0.0  0.258106  0.502849
10  0.0  0.380678  ...  3.119041  0.466770  0.301885  0.0  0.148340  0.353260
20  0.0  0.372830  ...  3.061052  0.399158  0.290043  0.0  0.108559  0.323533
40  0.0  0.373159  ...  3.242268  0.392822  0.411980  0.0  0.107582  0.345735
60  0.0  0.361015  ...  3.171247  0.390550  0.286994  0.0  0.100205  0.354976

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.187796
10  0.0  0.101911  0.0  0.174853
20  0.0  0.115700  0.0  0.176397
40  0.0  0.114785  0.0  0.174730
60  0.0  0.108202  0.0  0.183434

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    10
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     60
ABT     60
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    10
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-05-25
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-05-26:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.955574  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.856708  1.171461   0.0  0.618837  0.0  0.187910  2.808797  0.710107
20  0.912901  1.043817   0.0  0.355543  0.0  0.122331  2.913773  0.737961
40  0.916273  1.090748   0.0  0.349974  0.0  0.132909  3.143382  0.710380
60  0.916638  1.091238   0.0  0.338639  0.0  0.122475  3.075938  0.737523

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.236577  0.425937  0.910756  0.0  0.258106  0.502849
10  0.0  0.380678  ...  3.119041  0.466770  0.301885  0.0  0.148340  0.353260
20  0.0  0.372830  ...  3.061052  0.399158  0.290043  0.0  0.108559  0.474633
40  0.0  0.373159  ...  3.242268  0.392822  0.411980  0.0  0.107582  0.345735
60  0.0  0.388539  ...  3.171247  0.422217  0.328837  0.0  0.107417  0.354976

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.187796
10  0.0  0.172568  0.0  0.174853
20  0.0  0.115700  0.0  0.176397
40  0.0  0.114785  0.0  0.198637
60  0.0  0.108202  0.0  0.183434

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM     10
ABT     20
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA    40
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-05-26
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-30:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.955574  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.911988  1.171461   0.0  0.618837  0.0  0.187910  2.876005  0.747523
20  0.912901  1.193997   0.0  0.355543  0.0  0.194494  2.913773  0.737961
40  0.916273  1.090748   0.0  0.349974  0.0  0.132909  3.143382  0.710380
60  0.916638  1.091238   0.0  0.379452  0.0  0.122475  3.075938  0.737523

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.236577  0.425937  0.910756  0.0  0.258106  0.502849
10  0.0  0.380678  ...  3.119041  0.466770  0.301885  0.0  0.148340  0.353260
20  0.0  0.378844  ...  3.363860  0.399158  0.303381  0.0  0.108559  0.474633
40  0.0  0.373159  ...  3.242268  0.456242  0.411980  0.0  0.107582  0.486480
60  0.0  0.388539  ...  3.171247  0.422217  0.328837  0.0  0.111844  0.354976

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.187796
10  0.0  0.172568  0.0  0.195838
20  0.0  0.115700  0.0  0.176397
40  0.0  0.114785  0.0  0.198637
60  0.0  0.122962  0.0  0.183434

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     10
ABT     40
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    10
ZBH      5
ZION    40
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-05-30
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-05-31:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.955574  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.956320  1.171461   0.0  0.618837  0.0  0.187910  3.373141  0.747523
20  0.912901  1.193997   0.0  0.355543  0.0  0.194494  2.913773  0.737961
40  0.916273  1.219025   0.0  0.367143  0.0  0.132909  3.143382  1.028991
60  0.916638  1.091238   0.0  0.379452  0.0  0.127317  3.075938  0.737523

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.236577  0.425937  0.910756  0.0  0.258106  0.502849
10  0.0  0.380678  ...  3.425780  0.466770  0.438756  0.0  0.148340  0.935982
20  0.0  0.378844  ...  3.363860  0.479916  0.303381  0.0  0.108559  0.474633
40  0.0  0.398950  ...  3.242268  0.456242  0.411980  0.0  0.128174  0.486480
60  0.0  0.388539  ...  3.171247  0.422217  0.328837  0.0  0.111844  0.354976

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.187796
10  0.0  0.172568  0.0  0.195838
20  0.0  0.115700  0.0  0.192974
40  0.0  0.149847  0.0  0.198637
60  0.0  0.122962  0.0  0.183434

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     60
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    20
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     20
ABT     60
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    20
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-05-31
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-06-01:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.955574  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.956320  1.171461   0.0  0.618837  0.0  0.187910  3.373141  0.747523
20  0.994466  1.193997   0.0  0.359559  0.0  0.194494  3.095779  0.737961
40  0.916273  1.219025   0.0  0.367143  0.0  0.132909  3.143382  1.028991
60  0.916638  1.214278   0.0  0.379452  0.0  0.127319  3.075938  0.809691

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.236577  0.425937  0.910756  0.0  0.258106  0.502849
10  0.0  0.380678  ...  3.425780  0.466770  0.438756  0.0  0.148340  0.935982
20  0.0  0.386202  ...  3.363860  0.479916  0.332464  0.0  0.154627  0.474633
40  0.0  0.398950  ...  3.242268  0.456242  0.411980  0.0  0.128174  0.486480
60  0.0  0.388539  ...  3.503664  0.456151  0.328837  0.0  0.111844  0.390623

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.187796
10  0.0  0.172568  0.0  0.195838
20  0.0  0.126351  0.0  0.192974
40  0.0  0.149847  0.0  0.198637
60  0.0  0.122962  0.0  0.202948

[5 rows x 506 columns]
W.idxmin(): MMM     40
ABT     10
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
min window: MMM     40
ABT     10
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    60
ZTS      5
SPY      5
Length: 506, dtype: int64
ABBV ==================
2000-06-01
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-06-02:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.955574  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.956320  1.384174   0.0  0.618837  0.0  0.187910  3.373141  0.747523
20  0.994466  1.193997   0.0  0.371008  0.0  0.194494  3.095779  0.926597
40  1.033400  1.219025   0.0  0.367143  0.0  0.132909  3.143382  1.028991
60  0.916638  1.214278   0.0  0.379452  0.0  0.127800  3.489130  0.809691

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.478708  0.560210  0.910756  0.0  0.258106  0.502849
10  0.0  0.429190  ...  3.425780  0.466770  0.438756  0.0  0.148340  0.935982
20  0.0  0.386202  ...  3.363860  0.479916  0.332464  0.0  0.154627  0.474633
40  0.0  0.398950  ...  3.242268  0.456242  0.411980  0.0  0.128174  0.486480
60  0.0  0.388539  ...  3.503664  0.456151  0.389344  0.0  0.113667  0.454025

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.205538
10  0.0  0.172568  0.0  0.195838
20  0.0  0.126351  0.0  0.192974
40  0.0  0.149847  0.0  0.198637
60  0.0  0.135896  0.0  0.202948

[5 rows x 506 columns]
W.idxmin(): MMM     60
ABT     20
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
min window: MMM     60
ABT     20
ABBV     5
ABMD    40
ACN      5
        ..
ZBRA    60
ZBH      5
ZION    20
ZTS      5
SPY     20
Length: 506, dtype: int64
ABBV ==================
2000-06-02
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

//////////////////////////////////
W on 2000-06-05:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   0.955574  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.956320  1.384174   0.0  0.618837  0.0  0.187910  3.373141  0.989728
20  0.994466  1.375141   0.0  0.371008  0.0  0.194494  3.312101  0.926597
40  1.033400  1.219025   0.0  0.409483  0.0  0.132909  3.143382  1.028991
60  1.024350  1.214278   0.0  0.379452  0.0  0.139164  3.489130  0.809691

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.478708  0.560210  0.910756  0.0  0.258106  0.502849
10  0.0  0.429190  ...  3.425780  0.466770  0.438756  0.0  0.148340  0.935982
20  0.0  0.388533  ...  3.363860  0.479916  0.406965  0.0  0.154627  0.474633
40  0.0  0.398950  ...  3.585641  0.456242  0.411980  0.0  0.128174  0.486480
60  0.0  0.388539  ...  3.503664  0.496071  0.389344  0.0  0.115857  0.512868

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.205538
10  0.0  0.172568  0.0  0.195838
20  0.0  0.154325  0.0  0.214253
40  0.0  0.149847  0.0  0.198637
60  0.0  0.135896  0.0  0.202948

[5 rows x 506 columns]
W.idxmin(): MMM      5
ABT     60
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
min window: MMM      5
ABT     60
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    20
ZBH      5
ZION    60
ZTS      5
SPY     10
Length: 506, dtype: int64
ABBV ==================
2000-06-05
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-06-06:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   1.048236  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.872812
10  0.956320  1.384174   0.0  0.618837  0.0  0.187910  3.373141  0.989728
20  0.994466  1.375141   0.0  0.377404  0.0  0.194494  3.312101  0.926597
40  1.033400  1.219025   0.0  0.409483  0.0  0.145157  3.637799  1.028991
60  1.024350  1.330472   0.0  0.379452  0.0  0.139164  3.489130  0.938309

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.478708  0.560210  0.910756  0.0  0.258106  0.502849
10  0.0  0.429190  ...  3.425780  0.466770  0.438756  0.0  0.148340  0.935982
20  0.0  0.396381  ...  3.689376  0.479916  0.406965  0.0  0.154627  0.755863
40  0.0  0.398950  ...  3.585641  0.514894  0.411980  0.0  0.128174  0.486480
60  0.0  0.388539  ...  3.503664  0.496071  0.431068  0.0  0.121016  0.512868

    ZBH      ZION  ZTS       SPY
5   0.0  0.139633  0.0  0.205538
10  0.0  0.172568  0.0  0.216135
20  0.0  0.154325  0.0  0.214253
40  0.0  0.149847  0.0  0.198637
60  0.0  0.153430  0.0  0.202948

[5 rows x 506 columns]
W.idxmin(): MMM     10
ABT     40
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    40
ZBH      5
ZION     5
ZTS      5
SPY     40
Length: 506, dtype: int64
min window: MMM     10
ABT     40
ABBV     5
ABMD    20
ACN      5
        ..
ZBRA    40
ZBH      5
ZION     5
ZTS      5
SPY     40
Length: 506, dtype: int64
ABBV ==================
2000-06-06
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================
//////////////////////////////////
W on 2000-06-07:          MMM       ABT  ABBV      ABMD  ACN      ATVI      ADBE       AMD  \
5   1.048236  1.729862   0.0  0.763110  0.0  5.668286  7.240056  0.878001
10  1.034879  1.384174   0.0  0.618837  0.0  0.187910  3.373141  0.989728
20  0.994466  1.375141   0.0  0.389012  0.0  0.194494  3.384289  0.926597
40  1.033400  1.321706   0.0  0.409483  0.0  0.145157  3.637799  1.028991
60  1.024350  1.330472   0.0  0.379452  0.0  0.140130  3.489130  0.938309

    AAP       AES  ...       XEL       XRX      XLNX  XYL       YUM      ZBRA  \
5   0.0  0.526263  ...  3.478708  0.560210  0.910756  0.0  0.258106  0.502849
10  0.0  0.429190  ...  3.675692  0.561827  0.438756  0.0  0.148340  0.935982
20  0.0  0.396381  ...  3.689376  0.479916  0.461874  0.0  0.154627  0.755863
40  0.0  0.398950  ...  3.585641  0.514894  0.411980  0.0  0.128174  0.607416
60  0.0  0.407509  ...  3.503664  0.496071  0.431068  0.0  0.125768  0.512868

    ZBH      ZION  ZTS       SPY
5   0.0  0.139669  0.0  0.205538
10  0.0  0.172568  0.0  0.216135
20  0.0  0.154325  0.0  0.214253
40  0.0  0.149847  0.0  0.218689
60  0.0  0.153430  0.0  0.202948

[5 rows x 506 columns]
W.idxmin(): MMM     20
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA     5
ZBH      5
ZION     5
ZTS      5
SPY     60
Length: 506, dtype: int64
min window: MMM     20
ABT     40
ABBV     5
ABMD    60
ACN      5
        ..
ZBRA     5
ZBH      5
ZION     5
ZTS      5
SPY     60
Length: 506, dtype: int64
ABBV ==================
2000-06-07
Date
2000-01-03         NaN
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
                ...
2020-11-30    0.043434
2020-12-01    0.041023
2020-12-02    0.062181
2020-12-03    0.103079
2020-12-04    0.339749
Length: 5266, dtype: float64
5     0.0
10    0.0
20    0.0
40    0.0
60    0.0
Name: ABBV, dtype: float64
ABBV ==================

### Random Forest ###

In [ ]:
import numpy as np

windows = [5,10,20,40,60]
min_windows = pd.DataFrame().reindex_like(daily_return_df)
concat = None
for w in windows:
    beta_df = daily_return_df.rolling(window=w).cov(daily_return_df['SPY']).div(daily_return_df['SPY'].rolling(window=w).var(), axis=0)
    act_beta_error_df = (daily_return_df - beta_df.mul(daily_return_df['SPY'].mean(), axis=0)) ** 2    
    act_beta_error_df.columns = act_beta_error_df.columns + "_{0}".format(w)
    if concat is not None:
        concat = pd.concat([concat,act_beta_error_df], axis=1)
    else:
        concat = act_beta_error_df
concat

In [378]:
min_windows = pd.DataFrame()
for ticker in daily_return_df.columns:
    prefix = ticker + '_'
    head = [prefix + "5", prefix + "10", prefix + "20", prefix + "40", prefix + "60"]
    min_windows[ticker] = concat[head].idxmin(axis=1).str.replace(prefix,"")
min_windows

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,XEL,XRX,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS,SPY
Date,,,,,,,,,,,,,,,,,,,,,
1/2/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/3/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/6/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/7/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/8/2020,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11/20/2020,10,5,40,20,10,5,40,10,5,5,...,10,5,10,5,20,40,5,5,5,5
11/23/2020,20,20,5,20,10,20,40,10,40,5,...,5,10,10,5,5,40,10,5,10,40
11/24/2020,20,20,5,20,10,20,20,10,40,20,...,40,10,10,10,10,5,40,5,10,5
11/25/2020,20,5,10,20,20,10,20,60,10,60,...,5,10,60,60,20,40,10,10,5,5
11/27/2020,5,10,5,60,5,10,20,5,10,10,...,5,20,60,60,5,40,20,20,5,5

In [379]:

d = pd.DataFrame(np.zeros((df.shape)), index=df.index, columns=df.columns)

cumsum_df = daily_return_df.cumsum(axis=0) #vegtelen ablak
print(cumsum_df)
# cumsum_df = daily_return_df.rolling(window=100) #rolling min (nem az egeszen, csak pl 100 napon)
# # melyikre teljes\t jobban? fel-1-20... evek vagy a vegtelen
# # follow the leader x ev
# # ftl vegtelen, stb.

# #cumsum.idxmin(axis=1)
# #print(d)
# for ind,row in cumsum_df.idxmin(axis=1).items():
#     #print(ind)
#     #print(row)
#     d.loc[ind,row] = 1

# shifted = d.shift(1) # Mert a tegnapig kapott adatokat nezzuk
# shifted = shifted.mul(df)
# print(df.tail())
# print(df.shift(1).tail())
# shifted.sum(axis=1).cumsum().plot()
# cumsum_df["follow the leader"] = shifted.sum(axis=1).cumsum()
# cumsum_df

# # A mai legjobbat a holnapi legjobbal kell szamolni: shift 1

# # Feature set a kapott beta ablakokkal minden evre, minden modell csak a sajat evet nezi
# # melyik nap 
# # volatilis iszoszakok: beta ablak
# # X: amit felhasznalok feature, Y: a kimenet
# # X-et kitalalom pl. az elmult valamennyi nap alapjan a tulajdonsagok
# # minden napra visszamegyek egy param pl 5 napot, es 
# # daily return, szoras
# # beta window melle a volume


# # kiszamolni minden reszvenyre egy napon belul a legjobb window
# # minden reszveny, datum-ra minden window, es a legkisebbet veszem
# # shift ide nem kell

                 MMM       ABT      ABBV      ABMD       ACN      ATVI  \
Date
1/2/2020    0.013057  0.010342  0.005276 -0.021448 -0.003367 -0.021032
1/3/2020    0.021135  0.011974  0.011287 -0.021508  0.002868 -0.010003
1/6/2020    0.029433  0.020383  0.024663  0.053614  0.003636  0.011718
1/7/2020    0.027302  0.021433  0.024213  0.062113  0.007229  0.022607
1/8/2020    0.042077  0.021085  0.028363  0.063851  0.008846  0.020607
...              ...       ...       ...       ...       ...       ...
11/20/2020 -0.229102  0.119007 -0.080462  0.670294  0.258689  0.215344
11/23/2020 -0.226915  0.099622 -0.078108  0.664065  0.264778  0.202343
11/24/2020 -0.215029  0.084070 -0.067610  0.661175  0.275247  0.193124
11/25/2020 -0.213446  0.078092 -0.063950  0.654175  0.272567  0.200763
11/27/2020 -0.218676  0.086998 -0.064808  0.684099  0.272726  0.206426

                ADBE       AMD       AAP       AES  ...       XEL       XRX  \
Date                                                ...
1/2/2020    0.013424  0.047802 -0.006606  0.003005  ... -0.018411 -0.004314
1/3/2020    0.021444  0.059669  0.002190 -0.001520  ... -0.011988 -0.000182
1/6/2020    0.037954  0.067375 -0.003769  0.012657  ... -0.014697 -0.005446
1/7/2020    0.035680  0.045085 -0.016261  0.016653  ... -0.009709 -0.008220
1/8/2020    0.047842  0.044667 -0.027175  0.012681  ... -0.012744 -0.007663
...              ...       ...       ...       ...  ...       ...       ...
11/20/2020  0.212315  0.232695 -0.339508  0.100708  ...  0.247782 -0.436026
11/23/2020  0.203663  0.230240 -0.321535  0.093430  ...  0.228839 -0.417541
11/24/2020  0.206459  0.222657 -0.303184  0.114183  ...  0.221988 -0.400263
11/25/2020  0.214587  0.233734 -0.310097  0.106145  ...  0.220961 -0.395967
11/27/2020  0.214860  0.224642 -0.312160  0.104247  ...  0.210716 -0.400255

                XLNX       XYL       YUM      ZBRA       ZBH      ZION  \
Date
1/2/2020    0.025214  0.008716  0.012587  0.000425 -0.005201  0.001528
1/3/2020    0.012882  0.025039  0.016826  0.000229  0.004228  0.007169
1/6/2020    0.006750  0.024288  0.020376  0.021566  0.000055  0.006973
1/7/2020    0.019374  0.019157  0.022538  0.017566 -0.004859  0.006382
1/8/2020    0.017563  0.020538  0.039259  0.003080  0.003499  0.013455
...              ...       ...       ...       ...       ...       ...
11/20/2020  0.508396  0.443384  0.050273  0.227411 -0.123044 -0.134808
11/23/2020  0.507347  0.436567  0.044686  0.215398 -0.125296 -0.119147
11/24/2020  0.500636  0.450921  0.058974  0.227978 -0.102065 -0.084033
11/25/2020  0.512278  0.443326  0.056168  0.220099 -0.106786 -0.082321
11/27/2020  0.514173  0.441066  0.057850  0.220046 -0.109843 -0.106554

                 ZTS       SPY
Date
1/2/2020    0.015827  0.004111
1/3/2020    0.028509  0.008003
1/6/2020    0.023650  0.017832
1/7/2020    0.028011  0.016934
1/8/2020    0.024497  0.021610
...              ...       ...
11/20/2020  0.192281  0.032182
11/23/2020  0.181387  0.032686
11/24/2020  0.161131  0.041042
11/25/2020  0.150019  0.039748
11/27/2020  0.149091  0.039281

[230 rows x 506 columns]

AttributeError: 'Rolling' object has no attribute 'idxmin'

In [ ]:
cumsum_df

In [ ]:
# X feature 
# shift-el veszem az elozo x napot, 
pd.DataFrame({"returns" : daily_return_df.stack(), "shifted returns": daily_return_df.shift(1).stack()})
# X feature volume, rolling 
#

In [ ]:
daily_return_df.rolling(10).std()
# szoras, vagy 
daily_return_df.rolling(10).mean()
# Ezekbol csinalom az X-et

# X-bol az Y-t random forest-el szamolom
# A holnapi Y-t a mai X-hez: shift -1 (indexek stimmeljenek)
# Az Y az optimalis window merete

#FTL: minden reszvenyre kell az optimalis window
# --> a kovetkezonek minek kellene lennie

# random forest: default
# szimulacio: megtanitom pl 10-ig(traning), es utana 20-ig(test) ellenorzom
from sicklearn import randomforest
# fit # predict

## step:
# ftl osszehasonlitasa a window-kra, es a vegtelenre
# beta error reszvenyenkent minden ablakra 
## ez lesz az X (+ egy szorast, meg egy arfolyamerteket min, max, volume)
## Y a beta_error reszvenyenkent
# Y minden napra minden reszvenyre kiszamolom az osszes beta window hibajat, es a legkisebb ablakja lesz az Y
# Egy napon belülre számolom az értékeket: 5 érték 

# Fix es X es Y ertekeket megetetetek a random forest-el