### Best window for all ticker ###

In [346]:
import numpy as np

windows = [5,10,20,40,60]
min_windows = pd.DataFrame().reindex_like(daily_return_df)
prev_beta_error_df = None
concat = None
for w in windows:
    beta_df = daily_return_df.rolling(window=w).cov(daily_return_df['SPY']).div(daily_return_df['SPY'].rolling(window=w).var(), axis=0)
    act_beta_error_df = (daily_return_df - beta_df.mul(daily_return_df['SPY'].mean(), axis=0)) ** 2    
    act_beta_error_df.columns = act_beta_error_df.columns + "_{0}".format(w)
    if concat is not None:
        concat = pd.concat([concat,act_beta_error_df], axis=1)
    else:
        concat = act_beta_error_df
concat

,MMM_5,ABT_5,ABBV_5,ABMD_5,ACN_5,ATVI_5,ADBE_5,AMD_5,AAP_5,AES_5,...,XEL_60,XRX_60,XLNX_60,XYL_60,YUM_60,ZBRA_60,ZBH_60,ZION_60,ZTS_60,SPY_60
Date,,,,,,,,,,,,,,,,,,,,,
1/2/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/3/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/6/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/7/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/8/2020,0.000213,2.110161e-07,1.546639e-05,4.015859e-07,2.770852e-06,0.000005,1.407871e-04,7.069349e-07,0.000121,0.000017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11/20/2020,0.000063,9.875417e-07,7.836516e-05,7.779479e-05,5.149185e-06,0.000208,2.554870e-05,6.194058e-05,0.000115,0.000223,...,6.727225e-10,0.000045,0.000008,0.000004,0.000003,5.482825e-04,0.000001,0.000050,0.000017,3.894700e-05
11/23/2020,0.000004,3.873034e-04,4.914337e-06,4.137345e-05,3.476339e-05,0.000175,7.935690e-05,7.527488e-06,0.000322,0.000052,...,3.633239e-04,0.000336,0.000002,0.000048,0.000033,1.496023e-04,0.000006,0.000243,0.000123,1.108893e-07
11/24/2020,0.000137,2.471371e-04,1.070634e-04,9.129314e-06,1.056217e-04,0.000087,6.840774e-06,6.006421e-05,0.000332,0.000428,...,4.851106e-05,0.000293,0.000048,0.000202,0.000200,1.528029e-04,0.000533,0.001228,0.000417,6.700206e-05
11/25/2020,0.000002,3.516814e-05,1.308463e-05,5.185756e-05,8.028811e-06,0.000060,6.389913e-05,1.184563e-04,0.000051,0.000069,...,1.309120e-06,0.000017,0.000131,0.000060,0.000009,6.561605e-05,0.000024,0.000003,0.000127,2.146493e-06
11/27/2020,0.000028,8.323127e-05,8.053154e-07,8.936498e-04,1.510583e-11,0.000035,4.526880e-08,8.192247e-05,0.000006,0.000005,...,1.071439e-04,0.000020,0.000003,0.000006,0.000002,7.450207e-08,0.000010,0.000591,0.000001,4.070140e-07

In [378]:
min_windows = pd.DataFrame()
for ticker in daily_return_df.columns:
    prefix = ticker + '_'
    head = [prefix + "5", prefix + "10", prefix + "20", prefix + "40", prefix + "60"]
    min_windows[ticker] = concat[head].idxmin(axis=1).str.replace(prefix,"")
min_windows

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,XEL,XRX,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS,SPY
Date,,,,,,,,,,,,,,,,,,,,,
1/2/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/3/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/6/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/7/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1/8/2020,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11/20/2020,10,5,40,20,10,5,40,10,5,5,...,10,5,10,5,20,40,5,5,5,5
11/23/2020,20,20,5,20,10,20,40,10,40,5,...,5,10,10,5,5,40,10,5,10,40
11/24/2020,20,20,5,20,10,20,20,10,40,20,...,40,10,10,10,10,5,40,5,10,5
11/25/2020,20,5,10,20,20,10,20,60,10,60,...,5,10,60,60,20,40,10,10,5,5
11/27/2020,5,10,5,60,5,10,20,5,10,10,...,5,20,60,60,5,40,20,20,5,5